# -*- coding: utf-8 -*-
"""7may.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lt0cAS1uGibKHpyOItRoTOKtVskkGQHL
"""

print("hell world")

address="""raj
shiv
nihal"""

print(address)

'''
comment
raj
sss
'''

print ("hello")

company='xyz'
year=2024
print(f"company name{company},year name{year}")

print("hello world")

print('''raj
shiv
rahul''')

company='regex'
year=2024
print(f"company name is {company},year name{year}")

'''comment hello bhai kesa h'''

#comment

print("hello\n word")
print ("hey kishan")

from google.colab import drive
drive.mount('/content/drive')

print ("hello world",end="--")
print ("hey kishan")
print("user")

print ("hello"," world",sep="$")

age=21
print(age)

print(type(age))

city='jaipur'
print(type(city))

address='''plot no.
city
state'''
print(address)

#hey raj

''''hey raj
kishan'''

#string formatting

name='kishan'
age=21
print(f" my name is {name}my age is{age}")

username="aman"
msg=f"hello user{username}"
username="kishan"
print(msg)

#.format method
print("companyname is{}year is {} ".format("abc",2024))

print("companyname is{1}year is {0} ".format("abc",2024))

